name: investor-intelligence
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - setuptools
  - wheel
  - pip:
    - mcp>=1.0.0
    - pydantic>=2.0.0
    - python-dotenv>=1.0.0
    - pyyaml>=6.0
    - aiohttp>=3.8.0
    - pytest>=7.0.0
    - pytest-asyncio>=0.21.0
    - black>=22.0.0
    - flake8>=5.0.0
    - mypy>=1.0.0
