name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Install package in editable mode
        run: pip install -e src

      - name: Run tests
        run: |
          pytest

    # Optional: Add steps for linting, code style checks, etc.
    # - name: Run linter
    #   run: |
    #     pip install flake8
    #     flake8 .

  # Optional: Add a deployment job if you have a deployment target (e.g., Docker Hub, AWS EC2)
  # deploy:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest
  #   if: github.ref == \'refs/heads/main\'
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #   - name: Build and push Docker image
  #     uses: docker/build-push-action@v2
  #     with:
  #       context: .
  #       push: true
  #       tags: your_docker_username/investor-intelligence-mcp:latest
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKER_PASSWORD }}
